<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1 (Total recall)**

Purely from memory, write short descriptions of the following terms:
<br>If you cannot recall the answers, please refer to the notes and put this information you could not recall in italics.
|**Term**|**Brief description**|
|:--|:--|
|Subsetting|select|
|Indexing|select a specific element in the list/array|
|Slicing|select a range of elements from the list/array|
|Masking|select elements from an array based one a certain criterion|

**Exercise 2 (Show me the ‘odd’ letters)**
<br>Use masking to subset the letters that correspond to the odd numbers. I.e., get the result `[A, C, E, G, I]`.

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

1. Subset all the first elements.
    * You should get array(`['1', '3', '2', ..., '10', '9']`)
2. Convert this to integers using astype(int)
    * You must look up how astype() works.
3. Use % to get the remainder for division by 2.
    * You should get array(`[1, 1, 0, ..., 0, 1]`).
4. Use the previous result to create a mask that checks if the remainder is zero or not
    * You should get array(`True, True, False, ..., False, True`]).
    * Now you have identified the locations of the odd numbers.
5. Use the mask and extract the corresponding second elements.


In [3]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [4]:
np_array_2d[:, 0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [20]:
df = np_array_2d[:, 0]
array2 = df.astype('int64')  # dataframe.astype(dtype, copy, errors)
array2

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [26]:
array3 = array2%2
array3 

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [27]:
my_mask = array3 > 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [28]:
np_array_2d[my_mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')