<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [3]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

Three ways to select a subset of data:
1. Subsetting: select
2. indexing:selecting one element
3. slicing: selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

|**Syntax**|**Result**|**Note**|
|:--|:--|:--|
|`x[0]`|First element`a1`||
|`x[-1]`|Last element`j10`||
|`x[0:3]`|Index 0 to 2`['a1','b2','c3']`|Gives 3−0=3 elements|
|`x[1:6]`|Index 1 to 5	`['b2','c3','d4','e5','f6']`|Gives 6-1=5 elements|
|`x[1:6:2]`|Index 1 to 5 in steps of 2	`['b2','d4','f6']`|Gives every other of 6-1=5 elements|
|`x[5:]`|	Index 5 to the end	`['f6','g7','h8','i9','j10']`|Gives `len(x)`- 5 =5 elements|
|`x[:5]`|Index 0 to 5	`['a1','b2','c3','d4','e5']`|Give 5-0 = 5 elements|
|`x[5:2:-1]`|Index 5 to 3 (i.e., in reverse)`['f6','e5','d4']`|Gives 5-2 = 3 elements|
|`x[::-1]`|Reverses the list	`['j10','i9','h8',...,'b2','a1']`||

In Python, If you slice with `[i:j]`, the slice will start at `i` and end at `j-1`, giving you a total of `j-i` elements.

## 1.2 Arrays only | Subsetting by masking

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

We can ask NumPy to **show me only those that are `True`** by:

In [9]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

Hence, the `True/False` answer acts like a mask allowing only the True subset to be seen.

Instead of creating another variable, we can also do this:

In [10]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

**Example 1**
<br> We can invert our mask by using the `~`.
<br>`~`  is called the Bitwise Not operator.

In [12]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

**Example 2**
<br> We can combine one mask **AND** another mask.
<br>(AND will show something only if both masks are true.)

In [13]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

**Example 3**
<br>We can combine one mask **OR** another mask.
<br>(OR will show something if either mask is true.)

In [11]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

**Take note:**
<br> 
* Always use the Bitwise NOT(~), Bitwise OR(|) and Bitwise AND(&) when combining masks with NumPy.
* Always use brackets to clarify what you are asking the mask to d

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

The differences between lists and arrays become more apparent with higher dimensional lists and arrays.

In [14]:
# 2D list:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

**Example 1**
<br> What is at position 4 (index 3)?

In [15]:
py_list_2d[3]

[4, 'D']

In [16]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

**Example 2**
<br> What is the FIRST element at position 4 (index 3)

In [17]:
py_list_2d[3][0]

4

In [18]:
np_array_2d[3, 0]

'4'

**Example 3**
<br> What are the first three elements?

In [19]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [20]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

**Example 4**

In [21]:
py_list_2d[:3][0]  # it gives the first of the list you get from py_list_2d[:3].

[1, 'A']

In [24]:
np_array_2d[:3, 0]  # notice this yields the first elements (i.e., [1, 2, 3]) of all the sub-lists up to index 2.

array(['1', '2', '3'], dtype='<U21')

**Example 5**

In [25]:
py_list_2d[3:6][0]

[4, 'D']

In [26]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [27]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

* Lists: ease and efficiency in growing
* Numpy arrays: fast math operations provided you do not change their size.

How to grow a list:

**Example 1**
<br> Creating a larger list from a smaller one

In [29]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

**Example 2**
<br> Three ways to grow a list by appending one element at a time

In [30]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [31]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [32]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

The execution speeds of the above three methods are different; the version with append() runs about 1.5 times faster than the rest!

**Example 3**
<br> Here are three ways of incorporating multiple elements.
<br> Notice the difference between the effects of `extend()` and `append()`.

In [33]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [34]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [35]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

Another data storage structure: **tuple**. 
<br> Tuples are similar to lists, except they use `( )` and cannot be changed after creation (i.e., they are immutable).

In [36]:
a=(1, 2, 3)     # Define tuple

In [37]:
print(a[0])    # Access data

1


In [39]:
# The following will NOT work because we cannot change the data of a tuple
a[0]=-1  
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

Be careful when copying lists and arrays.

For example, if you want to copy a list, you might be tempted to do the following; PLEASE DON’T!

In [40]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

The correct way to do this is as follows:

In [44]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
z=x.copy()

must use `copy()` to be safe. reason: [mutable and immutable objects](https://phyweb.physics.nus.edu.sg/~chammika/sp2273/docs/python_basics/03_storing-data/2_storing-data_good.html#sec-python-variables)